apiVersion: v1
cloud:
  aws:
    region: "us-east-1"
    accessKeyID: ""
    secretAccessKey: ""
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  bootImageSpec:
    owners: "099720109477"
    filters: name=ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
  cloudInitFile: /etc/virtual-kubelet/cloudinit.yaml
  defaultInstanceType: "t3.nano"
  defaultVolumeSize: "20G"
  nametag: virtual-kubelet
  itzo:
    url: https://itzo-kip-download.s3.amazonaws.com
    version: latest
kubelet:
  cpu: "100"
  memory: "512Gi"
  pods: "200"
